In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("letter-recognition.data")

In [3]:
df

,T,2,8,3,5,1,8.1,13,0,6,6.1,10,8.2,0.1,8.3,0.2,8.4
0,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
1,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
2,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
3,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
4,S,4,11,5,8,3,8,8,6,9,5,6,6,0,8,9,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19995,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19996,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19997,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8


In [4]:
df.head()

,T,2,8,3,5,1,8.1,13,0,6,6.1,10,8.2,0.1,8.3,0.2,8.4
0,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
1,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
2,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
3,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
4,S,4,11,5,8,3,8,8,6,9,5,6,6,0,8,9,7


In [5]:
df.tail()

,T,2,8,3,5,1,8.1,13,0,6,6.1,10,8.2,0.1,8.3,0.2,8.4
19994,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19995,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19996,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19997,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19998,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8


In [6]:
df.shape

(19999, 17)

In [7]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [8]:
x

,2,8,3,5,1,8.1,13,0,6,6.1,10,8.2,0.1,8.3,0.2,8.4
0,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
1,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
2,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
3,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
4,4,11,5,8,3,8,8,6,9,5,6,6,0,8,9,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19995,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19996,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19997,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8


In [9]:
y

0        I
1        D
2        N
3        G
4        S
        ..
19994    D
19995    C
19996    T
19997    S
19998    A
Name: T, Length: 19999, dtype: object

In [10]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [11]:
y

array([ 8,  3, 13, ..., 19, 18,  0])

In [12]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
scalar = StandardScaler()

x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)

In [14]:
import tensorflow as tf;
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
model = Sequential()
model.add(Dense(128,activation='relu',input_shape=(16,)))
model.add(Dense(64,activation='relu'))
model.add(Dense(26,activation='softmax'))

C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [16]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [17]:
history = model.fit(
    x_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.1
)

Epoch 1/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.4292 - loss: 2.1383 - val_accuracy: 0.7650 - val_loss: 0.8507
Epoch 2/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7840 - loss: 0.7517 - val_accuracy: 0.8169 - val_loss: 0.6200
Epoch 3/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8426 - loss: 0.5482 - val_accuracy: 0.8487 - val_loss: 0.4997
Epoch 4/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8691 - loss: 0.4457 - val_accuracy: 0.8800 - val_loss: 0.4221
Epoch 5/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8893 - loss: 0.3763 - val_accuracy: 0.8788 - val_loss: 0.3694
Epoch 6/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9084 - loss: 0.3076 - val_accuracy: 0.9000 - val_loss: 0.3256
Epoch 7/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9233 - loss: 0.2569 - val_accuracy: 0.9075 - val_loss: 0.2960
Epoch 8/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9292 - loss: 0.2386 - val_accuracy: 0.

In [18]:
loss,accuracy = model.evaluate(x_test,y_test)

print("Accuracy: ",accuracy)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9399 - loss: 0.1818
Accuracy:  0.940500020980835


In [19]:
prediction = model.predict(x_test)
print(prediction[0])

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[5.4171375e-07 4.0760115e-04 6.7608004e-09 1.2798231e-06 3.1872885e-06
 1.4327426e-07 7.9337924e-06 1.3764047e-04 6.2703311e-06 1.4567505e-09
 6.7021261e-04 7.0751139e-06 4.9131506e-14 3.9290030e-10 1.4909615e-08
 3.9300767e-09 4.9058033e-09 1.8899634e-02 4.7988237e-07 3.5964740e-09
 7.8483424e-08 2.4184173e-08 2.4216225e-14 9.7985774e-01 1.2151588e-07
 3.1252367e-09]


In [20]:
predicted_class = np.argmax(prediction[0])

print(predicted_class)

23


In [21]:
letter = encoder.inverse_transform([predicted_class])

print(letter)

['X']


In [ ]:
"""This practical is about **Multiclass Classification using Deep Neural Networks (DNN)** using the **OCR Letter Recognition Dataset**.

The goal is:

* Input → features of a letter image
* Output → predict which letter it is (`A` to `Z`)

Since there are **26 possible classes**, this is called:

# Multiclass Classification

---

# 1. Importing Libraries

```python
import numpy as np
import pandas as pd
```

## What these do

### NumPy (`np`)

Used for:

* mathematical operations
* arrays
* handling predictions

### Pandas (`pd`)

Used for:

* reading dataset
* handling tables/dataframes

---

# 2. Reading Dataset

```python
df = pd.read_csv("letter-recognition.data")
```

## What happens here?

The dataset file is loaded into a dataframe named `df`.

Each row represents:

* one alphabet letter
* along with 16 numerical features describing it

---

# 3. Viewing Dataset

```python
df.head()
```

Shows first 5 rows.

```python
df.tail()
```

Shows last 5 rows.

```python
df.shape
```

Shows:

```python
(rows, columns)
```

For this dataset:

* 20,000 rows
* 17 columns

Why 17?

* 1 column → output letter
* 16 columns → input features

---

# 4. Splitting Input and Output

```python
x = df.iloc[:,1:]
y = df.iloc[:,0]
```

This is VERY IMPORTANT.

---

# Understanding `iloc`

`iloc` means:

# Integer Location

Used to select rows/columns using index numbers.

---

# Dataset Structure

| Column 0 | Column 1 | Column 2 | ... |
| -------- | -------- | -------- | --- |
| Letter   | Feature1 | Feature2 | ... |

---

# `x = df.iloc[:,1:]`

Meaning:

```python
[row selection , column selection]
```

### `:` before comma

means:

* select ALL rows

### `1:`

means:

* select columns from index 1 till end

So:

```python
x = input features
```

Contains:

* 16 numerical columns

---

# `y = df.iloc[:,0]`

Means:

* all rows
* only column 0

This is:

```python
A, B, C, D ...
```

Target/output labels.

---

# 5. Encoding Labels

```python
from sklearn.preprocessing import LabelEncoder
```

Neural networks cannot understand letters like:

```python
A B C
```

They only understand numbers.

---

## Creating Encoder

```python
encoder = LabelEncoder()
```

---

## Transforming Labels

```python
y = encoder.fit_transform(y)
```

Converts:

| Letter | Number |
| ------ | ------ |
| A      | 0      |
| B      | 1      |
| C      | 2      |
| ...    | ...    |
| Z      | 25     |

Now output becomes numeric.

---

# 6. Train-Test Split

```python
from sklearn.model_selection import train_test_split
```

---

## Why split data?

We divide dataset into:

| Part          | Purpose           |
| ------------- | ----------------- |
| Training Data | Learn patterns    |
| Testing Data  | Check performance |

---

## Splitting

```python
x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)
```

---

# Understanding Parameters

## `test_size=0.2`

20% data for testing.

80% for training.

If total rows = 20,000:

| Train  | Test  |
| ------ | ----- |
| 16,000 | 4,000 |

---

# `random_state=42`

Controls random splitting.

Without this:

* every run gives different train/test data

With this:

* same split every time

Useful for:

* reproducibility
* debugging
* comparing models

---

# Important Doubt

You asked earlier:

> "Doesn't random_state cause learning of training/testing data?"

NO.

It only fixes the random selection process.

The model STILL:

* trains only on training data
* never sees test labels during training

So no cheating happens.

---

# 7. Feature Scaling

```python
from sklearn.preprocessing import StandardScaler
```

---

# Why scaling?

Features may have different ranges.

Example:

| Feature | Values  |
| ------- | ------- |
| height  | 1-10    |
| area    | 100-500 |

Large values dominate learning.

So we normalize features.

---

# StandardScaler Formula

It transforms data using:

genui{"math_block_widget_always_prefetch_v2":{"content":"z = \frac{x-\mu}{\sigma}"}}

Where:

* (x) = original value
* (\mu) = mean
* (\sigma) = standard deviation

Result:

* mean becomes 0
* standard deviation becomes 1

---

# Scaling Training Data

```python
scalar = StandardScaler()

x_train = scalar.fit_transform(x_train)
```

---

# `fit_transform()`

Two steps:

1. Learn mean/std
2. Transform data

---

# VERY IMPORTANT MISTAKE IN YOUR CODE

You wrote:

```python
x_test = scalar.fit_transform(x_test)
```

This is WRONG.

Why?

Because test data should NOT calculate its own mean/std.

Correct:

```python
x_test = scalar.transform(x_test)
```

---

# Correct Version

```python
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)
```

---

# Why?

We want:

* training statistics used everywhere

Otherwise:

* data leakage happens
* evaluation becomes unrealistic

---

# 8. Importing TensorFlow

```python
import tensorflow as tf
```

TensorFlow is a deep learning framework.

Used to create:

* neural networks
* train models
* perform predictions

---

# 9. Creating Neural Network

```python
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
```

---

# Sequential Model

```python
model = Sequential()
```

Sequential means:

* layers connected one after another

---

# 10. First Hidden Layer

```python
model.add(Dense(128,activation='relu',input_shape=(16,)))
```

---

# Understanding This Layer

## Dense

Fully connected layer.

Every neuron connected to all previous neurons.

---

# `128`

Number of neurons.

This layer learns patterns from inputs.

---

# `input_shape=(16,)`

Because dataset has:

* 16 input features

So:

* 16 input neurons

---

# ReLU Activation

f(x)=\max(0,x)

If:

* x > 0 → output x
* x < 0 → output 0

Why used?

* avoids vanishing gradient
* faster training
* introduces non-linearity

---

# 11. Second Hidden Layer

```python
model.add(Dense(64,activation='relu'))
```

Another hidden layer:

* 64 neurons
* learns deeper patterns

---

# 12. Output Layer

```python
model.add(Dense(26,activation='softmax'))
```

---

# Why 26 neurons?

Because:

* 26 letters (A-Z)

Each neuron corresponds to one class.

---

# Softmax Activation

Converts outputs into probabilities.

Example:

| Letter | Probability |
| ------ | ----------- |
| A      | 0.01        |
| B      | 0.90        |
| C      | 0.03        |

All probabilities sum to 1.

---

# Softmax Formula

\sigma(z_i)=\frac{e^{z_i}}{\sum_{j=1}^{K}e^{z_j}}

---

# 13. Compiling Model

```python
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
```

---

# Optimizer = Adam

Adam updates weights efficiently.

It combines:

* Momentum
* RMSProp

Very popular optimizer.

---

# Loss Function

```python
sparse_categorical_crossentropy
```

Used because:

* multiclass classification
* labels are integers (0-25)

---

# Accuracy Metric

Measures:

* correct predictions percentage

---

# 14. Training Model

```python
history = model.fit(
    x_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.1
)
```

---

# Epochs

```python
epochs=20
```

One epoch:

* complete pass through training data

20 epochs:

* dataset processed 20 times

---

# Batch Size

```python
batch_size=32
```

Training happens in small groups of 32 samples.

Benefits:

* faster
* memory efficient

---

# Validation Split

```python
validation_split=0.1
```

10% of training data used for validation.

Validation checks:

* how model performs during training

---

# 15. Evaluating Model

```python
loss,accuracy = model.evaluate(x_test,y_test)
```

Checks performance on unseen test data.

---

# Printing Accuracy

```python
print("Accuracy: ",accuracy)
```

Usually gets:

* around 95%+

---

# 16. Making Predictions

```python
prediction = model.predict(x_test)
```

For every sample:

* outputs probabilities for 26 letters

---

# Example

```python
print(prediction[0])
```

Might show:

```python
[0.01 0.00 0.95 0.02 ...]
```

---

# Finding Highest Probability

```python
predicted_class = np.argmax(prediction[0])
```

`argmax()` returns:

* index of largest value

Example:

```python
[0.01 0.00 0.95]
```

Largest value index = 2

So predicted class = 2

---

# Converting Number Back to Letter

```python
letter = encoder.inverse_transform([predicted_class])
```

Converts:

```python
2 → C
```

---

# Final Flow of Practical

```text
Dataset
   ↓
Split input/output
   ↓
Encode labels
   ↓
Train-test split
   ↓
Feature scaling
   ↓
Build neural network
   ↓
Train model
   ↓
Evaluate accuracy
   ↓
Predict letters
```

---

# Why DNN Works Well Here

OCR letter recognition is complex because:

* different handwriting styles
* shapes vary
* many patterns

Deep Neural Networks:

* learn hidden patterns automatically
* perform well on image-like structured data

---

# Important Viva Questions

## What is multiclass classification?

Classification with more than two classes.

---

## Why use softmax?

To convert outputs into probabilities.

---

## Why use LabelEncoder?

Neural networks need numeric labels.

---

## Why scaling is important?

Prevents large-value features from dominating.

---

## Difference between ReLU and Softmax?

| ReLU              | Softmax                |
| ----------------- | ---------------------- |
| Hidden layers     | Output layer           |
| Removes negatives | Produces probabilities |

---

## Why sparse categorical crossentropy?

Because labels are integer encoded.
"""